### PR TITLE
mixer: fix output of list when have included bundles

### PR DESCRIPTION
**Pull request by cmarcelo**
Account for the size of included bundles for formatting the output of
list.

Before:

```
bootloader     (upstream)
c-basic        (upstream)
desktop        (upstream)
desktop-apps   (upstream) (included)
desktop-assets (upstream) (included)
desktop-gnomelibs (upstream) (included)
desktop-locales (upstream) (included)
kernel-native  (upstream)
libX11client   (upstream) (included)
os-core        (upstream)
os-core-update (upstream)
python3-basic  (upstream) (included)
sysadmin-basic (upstream) (included)
```

After:

```
bootloader        (upstream)
c-basic           (upstream)
desktop           (upstream)
desktop-apps      (upstream) (included)
desktop-assets    (upstream) (included)
desktop-gnomelibs (upstream) (included)
desktop-locales   (upstream) (included)
kernel-native     (upstream)
libX11client      (upstream) (included)
os-core           (upstream)
os-core-update    (upstream)
python3-basic     (upstream) (included)
sysadmin-basic    (upstream) (included)
```

Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

### CODE REVIEW

**Comment by kevincwells** [comment]
Hmm... good catch, but I"m not sure this is the right solution.

This has the unintended side effect of making `mixer bundle list local` print oddly. E.g.:

```
clr@machine /home/clr/mix # mixer bundle edit desktop
clr@machine /home/clr/mix # mixer bundle list local
desktop           (in mix) (masking upstream)
```

The reason is because, `mixer bundle list` is a list of _only_ the "available local bundles", and not a list of what those bundles themselves include. This patch uses the full list of the included bundles to set the width, and hence the above big gap (because it's formatting based on the length of `desktop-gnomelibs`).

**Comment by kevincwells** [comment]
FYI - with the code as it was (i.e., without this patch), only `mixer bundle list` is affected, because it's the only one of the three that is displaying included content too

**Comment by cmarcelo** [comment]
Yeah, I've overlooked that extra space. I'll try something else and we see if looks better.

**Comment by cmarcelo** [comment]
Could you take another look?

**Comment by kevincwells** [comment]
`tabwriter` -- cool library. Glad to know about it!

This is nice and clean. :+1:

**Pull request merged**
