### PR TITLE
swupd: add \n to warning printing

### PR DESCRIPTION
**Pull request by cmarcelo**
Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

### CODE REVIEW

**Comment by cmarcelo** [comment]
Haven't looked whether these should be printing or not, just ensuring they don't get in the way in testing output.

**Comment by matthewrsj** [comment]
This is poor error handling to begin with. I'd rather see a solution that fixes the `strings.Contains()` nastiness as well, which will probably make this `\n` fix obsolete.

My fault, I wrote this error handling. I remember you and @icarus-sparry had advice to fix it but I haven't gotten around to it.

**Comment by cmarcelo** [comment]
Should non hash calculation errors be ignored? Do you want a list of warnings in the end?

**Comment by matthewrsj** [comment]
Yes. The other errors that can occur on the file level are blacklisted filenames and unsupported file types. In those cases we should report them, but not fail the build. The blacklisted filenames happen (always? almost always?) often.

**Comment by cmarcelo** [comment]
> In those cases we should report them, but not fail the build

At the moment CreateManifests return a MoM and an error. Should it also return some kind of list of warnings (like we did for packs and fullfiles)?

**Comment by matthewrsj** [comment]
@cmarcelo yes I think that's a good idea.

**Comment by tmarcu** [comment]
Bump?

**Comment by cmarcelo** [comment]
I'm happy merging this (to avoid messing with go test output), and deal with improvements in a different PR.

**Pull request merged**
