### PR TITLE
[Do not merge; WIP] Move swupd-add-pkg from swupd-client into mixer-tools

### PR DESCRIPTION
**Pull request by tmarcu**
Signed-off-by: Tudor Marcu <tudor.marcu@intel.com>

### CODE REVIEW

**Comment by tmarcu** [comment]
https://github.com/clearlinux/swupd-client/pull/409 corresponding PR

**Comment by tmarcu** [comment]
Yes it does,I will create a more complete transition PR for this and swupd-client in the near future.

**Comment by matthewrsj** [comment]
Can this be closed now that `mixin` exists?

**Comment by matthewrsj** [comment]
This isn't happening any more. Closing because I'm tired of looking at it.

**Pull request closed without merging**
