### PR TITLE
build: Add root permission check

### LINKED ISSUE #690: Improve error handling when lacking permissions
Some Mixer commands require sudo, but the failures when sudo is not used can be misleading. For instance, `mixer build bundles` will fail to resolve packages, but it does not mention that this issue was caused by a lack of permissions. When Mixer commands require sudo, they should fail earlier with a more informative message.

### PR DESCRIPTION
**Pull request by jwakre**
Fixes #690

Changes proposed in this pull request:
* Add root permission check to `mixer build *` commands.

### CODE REVIEW

**Comment by rchiossi** [comment]
What about a `checkroot()` function instead?

**Comment by reaganlo** [comment]
I thought the checkroot() would be:
```
func checkRoot() {
	if uid := os.Geteuid(); uid != 0 {
		fail(errors.Errorf("This command requires root (uid=%d)\n", uid))
	}
}
```
and usage would just be calling `checkRoot()`

**Comment by jwakre** [comment]
> I thought the checkroot() would be:
> 
> ```
> func checkRoot() {
> 	if uid := os.Geteuid(); uid != 0 {
> 		fail(errors.Errorf("This command requires root (uid=%d)\n", uid))
> 	}
> }
> ```
> 
> and usage would just be calling `checkRoot()`

I thought about that, but I felt that it makes the code harder to read because it is not clear in the calling function that it can stop exection.

**Comment by reaganlo** [comment]
cool.. fair enough..

**Pull request merged**
