### PR TITLE
swupd: remove os-core-update-index file creation

### LINKED ISSUE #468: Stop creating `/usr/share/clear/os-core-update-index` file
This file is no longer used as the bundle-info themselves are published with much more information.

### PR DESCRIPTION
**Pull request by matthewrsj**
The file was no longer being used due to the actual bundle-info files
being published in the os-core-update-index bundle. Because this file is
very large and requires an update every version remove this file.

This commit also fixes a bug where the os-core-update-index bundle was
being created for every build, regardless of changes. This was not a
visibile bug when the os-core-update-index file itself was being created
because it had changes every time. Now that that file does not change
per release we should not be writing the manifest every time.

Fixes #468

### CODE REVIEW

**Comment by matthewrsj** [comment]
travis errors will be fixed by #466

**Comment by phmccarty** [comment]
In the second commit's commit message: s/visibile/visible

**Comment by matthewrsj** [comment]
@phmccarty fixed.

**Comment by matthewrsj** [comment]
travis error fixed.

**Pull request merged**
