### PR TITLE
swupd: export BundleInfo struct

### PR DESCRIPTION
**Pull request by matthewrsj**
This is useful for other projects trying to use the *-info file.

Signed-off-by: Matthew Johnson <matthew.johnson@intel.com>

### CODE REVIEW

**Comment by rchiossi** [comment]
lgtm

**Comment by matthewrsj** [comment]
hold off on this, I need to expose `getBundleInfo` as well, which means it needs to not take a swupd config argument.

**Comment by tmarcu** [comment]
@matthewrsj ping this again when it's ready to merge

**Comment by matthewrsj** [comment]
@tmarcu will do thanks.

**Comment by tmarcu** [comment]
@matthewrsj this good to go now it seems?

**Comment by matthewrsj** [comment]
Oh, thought this got merged already. Yes this is good to go.

**Comment by matthewrsj** [comment]
Rebased on latest (so I can use the other export from #393) in my local testing.

**Pull request merged**
